export type DocsIcon = "info" | "features" | "guide" | "database" | "api" | "security" | "notif" | "faq";

export interface DocsItem {
  id: string;
  sectionTitle: string;
  icon: DocsIcon;
  description: string;
  items: string[];
  sortOrder: number;
  isActive: boolean;
}

export const DOCS_DATA: DocsItem[] = [
  {
    id: "tentang-sitara",
    sectionTitle: "Tentang SITARA",
    icon: "info",
    description: "Pengenalan sistem dan tujuan utama.",
    items: [
      "**SITARA** adalah Sistem Informasi Tracking Reintegrasi Narapidana yang dikembangkan untuk Rumah Tahanan Negara Kelas IIB Wonosobo.",
      "Tujuan utama: memantau proses reintegrasi Warga Binaan secara transparan dan real-time.",
      "Dibangun dengan `Next.js 16`, `Supabase`, `Drizzle ORM`, dan `Tailwind CSS`.",
      "Mendukung 4 jenis layanan: **Pembebasan Bersyarat (PB)**, **Cuti Bersyarat (CB)**, **Cuti Menjelang Bebas (CMB)**, dan **Asimilasi**.",
      "Setiap Warga Binaan melewati 8 tahap proses dari verifikasi berkas hingga turun SK.",
    ],
    sortOrder: 0,
    isActive: true,
  },
  {
    id: "fitur-utama",
    sectionTitle: "Fitur Utama",
    icon: "features",
    description: "Kemampuan inti yang tersedia di SITARA.",
    items: [
      "**Tracking Publik** — Keluarga memantau status via kode tracking (`SITARA-XX-XXXXXXXX`) yang dikirim otomatis via WhatsApp.",
      "**Dashboard Admin** — Ringkasan statistik: total Warga Binaan, aktif, selesai, ditolak, distribusi per layanan dan tahap.",
      "**Manajemen Data** — CRUD lengkap data Warga Binaan dengan sanitasi otomatis (`toTitleCase`, normalisasi HP).",
      "**Notifikasi WhatsApp** — Kirim status terkini ke keluarga via **Fonnte API** dengan template pesan otomatis.",
      "**Buku Analisa** — Tabel proses 8 tahap dengan export XLSX dan cetak landscape.",
      "**Laporan** — Rekap data lengkap dengan filter status/layanan, export XLSX, dan cetak portrait.",
      "**QR Code** — Generate dan download QR code tracking untuk setiap Warga Binaan.",
      "**Riwayat Status** — Timeline perubahan tahap dengan keterangan dan timestamp.",
    ],
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "panduan-admin",
    sectionTitle: "Panduan Admin",
    icon: "guide",
    description: "Langkah-langkah operasional untuk petugas.",
    items: [
      "**Tambah Warga Binaan** — Buka menu `Data Warga Binaan` → klik `Tambah Warga Binaan` → isi form → simpan. Kode tracking otomatis di-generate.",
      "**Edit Data** — Klik nama Warga Binaan di tabel → ubah data di form → simpan. Perubahan tahap otomatis tercatat di riwayat.",
      "**Ubah Status** — Di tab `Status & Tahap`, pilih tahap baru atau ubah status ke `Selesai`/`Ditolak`. Jika ditolak, wajib isi alasan.",
      "**Kirim Notifikasi** — Klik tombol `Kirim Notif WA` di halaman edit atau daftar. Pesan dikirim ke nomor HP keluarga yang terdaftar.",
      "**Regenerate Kode** — Di sidebar edit, klik `Buat Kode Baru` jika kode lama perlu diganti. Kode lama otomatis tidak berlaku.",
      "**Export Data** — Di halaman Laporan atau Buku Analisa, klik `Unduh XLSX` untuk download spreadsheet.",
      "**Cetak** — Klik `Cetak` untuk membuka preview print yang hanya berisi data tabel (tanpa sidebar/header admin).",
    ],
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "panduan-tracking",
    sectionTitle: "Panduan Tracking Publik",
    icon: "guide",
    description: "Cara keluarga mengakses status reintegrasi.",
    items: [
      "Keluarga menerima kode tracking via WhatsApp saat Warga Binaan didaftarkan.",
      "Format kode: `SITARA-PB-A3K9X2M7` (jenis layanan + 8 karakter random).",
      "Buka halaman `/tracking` → masukkan kode → lihat status dan timeline proses.",
      "Halaman detail menampilkan: progress bar, timeline tahap, data pribadi, QR code, dan kontak keluarga.",
      "Jika status **Ditolak**, alasan penolakan ditampilkan di banner merah.",
      "QR code bisa di-scan untuk akses cepat ke halaman tracking.",
    ],
    sortOrder: 3,
    isActive: true,
  },
  {
    id: "struktur-database",
    sectionTitle: "Struktur Database",
    icon: "database",
    description: "Tabel dan relasi utama di Supabase.",
    items: [
      "Tabel `wbp` — Data utama Warga Binaan (nama, nomor registrasi, kode tracking, jenis layanan, tahap, status).",
      "Tabel `riwayat_status` — Log perubahan tahap dengan timestamp dan keterangan.",
      "Tabel `log_notifikasi` — Riwayat pengiriman WhatsApp (nomor, pesan, status kirim).",
      "Tabel `profiles` — Data admin/operator (nama, role: `super_admin`, `admin`, `operator`).",
      "Tabel `pengaturan` — Konfigurasi sistem (site config, fitur, layanan, tahapan).",
      "Relasi: `riwayat_status.wbp_id` → `wbp.id`, `log_notifikasi.wbp_id` → `wbp.id`.",
      "Auth menggunakan **Supabase Auth** dengan session cookie (`@supabase/ssr`).",
    ],
    sortOrder: 4,
    isActive: true,
  },
  {
    id: "api-endpoints",
    sectionTitle: "API Endpoints",
    icon: "api",
    description: "Daftar route API yang tersedia.",
    items: [
      "`GET /api/healthz` — Health check server.",
      "`POST /api/auth/login` — Login admin dengan email & password.",
      "`POST /api/auth/logout` — Logout dan hapus session.",
      "`GET /api/auth/me` — Data user yang sedang login.",
      "`GET /api/wbp` — List Warga Binaan (paginated, filterable).",
      "`POST /api/wbp` — Tambah Warga Binaan baru.",
      "`GET /api/wbp/:id` — Detail Warga Binaan + riwayat status.",
      "`PATCH /api/wbp/:id` — Update data Warga Binaan.",
      "`DELETE /api/wbp/:id` — Hapus Warga Binaan (admin/super_admin only).",
      "`POST /api/wbp/:id/regenerate-kode` — Generate kode tracking baru.",
      "`GET /api/tracking?q=KODE` — Search tracking publik (tanpa auth).",
      "`GET /api/tracking/:kode` — Detail tracking publik + riwayat.",
      "`GET /api/dashboard/stats` — Statistik dashboard.",
      "`GET /api/dashboard/recent` — 10 Warga Binaan terakhir diupdate.",
      "`POST /api/notifikasi` — Kirim notifikasi WhatsApp.",
      "`GET /api/riwayat/:wbpId` — Riwayat status per Warga Binaan.",
    ],
    sortOrder: 5,
    isActive: true,
  },
  {
    id: "keamanan",
    sectionTitle: "Keamanan & Akses",
    icon: "security",
    description: "Mekanisme proteksi data dan otorisasi.",
    items: [
      "Semua route admin dilindungi oleh `requireAuth()` — harus login.",
      "Role-based access: `super_admin` (full), `admin` (CRUD), `operator` (read + update).",
      "Hapus data hanya bisa dilakukan oleh `super_admin` atau `admin`.",
      "Tracking publik **tidak memerlukan login** — akses via kode tracking saja.",
      "Kode tracking bersifat rahasia — hanya dikirim ke nomor WA keluarga terdaftar.",
      "Security headers aktif: `HSTS`, `X-Frame-Options: DENY`, `X-Content-Type-Options: nosniff`.",
      "Session menggunakan HTTP-only cookie — tidak bisa diakses via JavaScript.",
      "Input disanitasi server-side sebelum disimpan ke database.",
    ],
    sortOrder: 6,
    isActive: true,
  },
  {
    id: "notifikasi-wa",
    sectionTitle: "Notifikasi WhatsApp",
    icon: "notif",
    description: "Konfigurasi dan cara kerja notifikasi.",
    items: [
      "Provider: **Fonnte** (`https://api.fonnte.com/send`).",
      "Token dikonfigurasi via environment variable `FONNTE_TOKEN`.",
      "Nomor HP otomatis dinormalisasi ke format `628xxx` (mendukung input `+62`, `08`, `62`, tanpa prefix).",
      "Template pesan berisi: nama Warga Binaan, jenis layanan, tahap terbaru, dan link tracking.",
      "Log pengiriman tersimpan di tabel `log_notifikasi` dengan status `terkirim` atau `gagal`.",
      "Jika `nomorTujuan` tidak dikirim, sistem otomatis menggunakan `nomorHpKeluarga` dari data Warga Binaan.",
    ],
    sortOrder: 7,
    isActive: true,
  },
  {
    id: "faq",
    sectionTitle: "FAQ",
    icon: "faq",
    description: "Pertanyaan yang sering diajukan.",
    items: [
      "**Q: Bagaimana jika kode tracking hilang?** — Admin bisa regenerate kode baru di halaman edit, lalu kirim ulang notifikasi WA.",
      "**Q: Apakah keluarga bisa melihat data pribadi lengkap?** — Tidak. Halaman publik hanya menampilkan nama, jenis kelamin, tempat/tanggal lahir, dan progress tahap.",
      "**Q: Bagaimana jika nomor WA keluarga berubah?** — Update di halaman edit Warga Binaan, tab Kontak. Nomor otomatis dinormalisasi.",
      "**Q: Siapa yang bisa menghapus data?** — Hanya `super_admin` dan `admin`. Operator tidak bisa menghapus.",
      "**Q: Apakah data bisa di-export?** — Ya, di halaman Laporan dan Buku Analisa tersedia tombol `Unduh XLSX`.",
      "**Q: Bagaimana cara menambah admin baru?** — Hubungi super_admin untuk membuat akun baru via Supabase Dashboard.",
    ],
    sortOrder: 8,
    isActive: true,
  },
];
